config/routes.rb
ActivityBlog::Application.routes.draw do
  
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  resources :posts do
    resources :comments, only: [:create, :update, :edit, :destroy]
  end


  get "/feed" => "activities#feed", as: :feed
  get "/feed/fetch" => "activities#show", as: :fetch_activity

  get "/yours" => "activities#yours", as: :your_actions

  get "/:nickname" => "users#show", as: :user

  root :to => "posts#index"
end

app/models/activity_observer.rb
class ActivityObserver < ActiveRecord::Observer
  observe PublicActivity::Activity

  # We are only sending the Activity's id through Pusher.
  # Then we retrieve the actual HTML of it by sending
  # an AJAX request from client using the supplied activity_id.
  # This is necessary, because activity has to be
  # rendered in client's session (we need current_user).
  def after_create(activity)
    Pusher['public_activity'].trigger('new-activity', {activity_id: activity.id})
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true

  default_scope :order => 'created_at ASC'

  belongs_to :user

  attr_accessible :user_id, :comment
end

app/models/comment_observer.rb
class CommentObserver < ActiveRecord::Observer
  include ActionView::Helpers::TextHelper

  def after_create(comment)
    comment.commentable.create_activity key: "post.commented", params: {comment: truncate(comment.comment, length: 30)}
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body, :title
  acts_as_commentable

  belongs_to :author, :class_name => "User"

  include PublicActivity::Model

  tracked :owner => proc {|controller, model| controller.current_user}, # set owner to current_user by default (check app/controllers/application_controller.rb)
          :params => {
            :summary => proc {|controller, model| controller.truncate(model.body, length: 30)}   # by default save truncated summary of the post's body
          }
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :nickname, :avatar_url, :password, :password_confirmation, :remember_me
  has_many :posts

  def to_param
    nickname
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  layout false, only: :show
  before_filter :authenticate_user!, only: :yours

  def feed
    @activities = PublicActivity::Activity.order("created_at DESC").all

    respond_to do |format|
      format.html
    end
  end

  def yours
    @activities = PublicActivity::Activity.order("created_at DESC").where(owner_type: "User", owner_id: current_user).all

    respond_to do |format|
      format.html
    end
  end

  def show
    @activity = PublicActivity::Activity.find(params[:id])

    respond_to do |format|
      format.html
    end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  # Necessary include if you plan on access controller instance
  # in Procs passed to #tracked method in your models
  include PublicActivity::StoreController
  include ActionView::Helpers::TextHelper  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def edit
    @comment = Comment.find(params[:id])
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment: params[:comment][:comment], user_id: current_user.id)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment.commentable, notice: 'Comment was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment.commentable, notice: 'Comment was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]


  # User's blog with only his posts
  def blog
    @user = User.where(nickname: params[:id]).first
  end

  def index
    @posts = Post.all

    respond_to do |format|
      format.html
    end
  end

  def show
    @post = Post.find(params[:id])
    @activities = PublicActivity::Activity.order("created_at DESC").where(trackable_type: "Post", trackable_id: @post).all
    @comment = Comment.new
    @comments = @post.comments
    respond_to do |format|
      format.html
    end
  end

  def new
    @post = Post.new

    respond_to do |format|
      format.html
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(params[:post])
    @post.author = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def github
    data = request.env["omniauth.auth"].extra.raw_info
    @user = User.where(email: data["email"]).first

    if @user
      @user.update_attributes(avatar_url: data.avatar_url, nickname: data.login)
    else
      @user = User.create nickname: data.nickname, email: data.email, password: Devise.friendly_token[0,20],
                          avatar_url: data.avatar_url, nickname: data.login
    end

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Github"
      sign_in_and_redirect @user, :event => :authentication
    else
      flash[:notice] = "Error while signing in with Github: #{@user.errors.to_a.join(",")}"

      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find_by_nickname params[:nickname]


    respond_to do |format|
      format.html
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # For generating time tags calculated using jquery.timeago
  def timeago(time, options = {})
    options[:class] ||= "timeago"
    content_tag(:abbr, time.to_s, options.merge(:title => time.getutc.iso8601)) if time
  end

  # Shortcut for outputing proper ownership of objects,
  # depending on who is looking
  def whose?(user, object)
    case object
      when Post
        owner = object.author
      when Comment
        owner = object.user
      else
        owner = nil
    end
    if user and owner
      if user.id == owner.id
        "his"
      else
        "#{owner.nickname}'s"
      end
    else
      ""
    end
  end

  # Check if object still exists in the database and display a link to it,
  # otherwise display a proper message about it.
  # This is used in activities that can refer to
  # objects which no longer exist, like removed posts.
  def link_to_trackable(object, object_type)
    if object
      link_to object_type.downcase, object
    else
      "a #{object_type.downcase} which does not exist anymore"
    end
  end
end

app/views/activities/feed.slim
- content_for :header, "News feed"

#activity-feed data-fetch-url=fetch_activity_path
- for activity in @activities
  = render_activity(activity, :layout => "layouts/activity_wrapper")

app/views/activities/show.slim
= render_activity(@activity, :layout => "layouts/activity_wrapper")

app/views/activities/yours.slim
- content_for :header, "Your actions"

- for activity in @activities
  = render_activity(activity, :layout => "layouts/activity_wrapper")

app/views/comments/_comment.slim
.activity.comment
  .body
    .title
      =' timeago comment.created_at, class: "timeago pull-right"
    .details
      .avatar
        = image_tag comment.user.avatar_url, width: "30", height: "30", title: comment.user.nickname

      = comment.comment

app/views/comments/_form.slim
= simple_form_for [@post, @comment] do |f|
  = f.input :comment, label: false
  .form-actions
    = f.button :submit, class: 'btn-success pull-right'

app/views/layouts/_activity_wrapper.slim
.activity
  .body
    .mega-icon style="background-image: url(#{image_path "icons/#{a.key}.svg"})"
    =' timeago a.created_at
    .title
      - if a.owner
        =' link_to a.owner.nickname, a.owner
      - else
        ' someone
      =' content_for :action
    .details
      .avatar
        - if a.owner
          = image_tag a.owner.avatar_url, width: "30", height: "30"
        - else
          = image_tag "http://i0.wp.com/a248.e.akamai.net/assets.github.com/images/gravatars/gravatar-140.png", width: "30", height: "30"
      = yield

app/views/layouts/application.slim
doctype html
html
  head
  title PublicActivity Blog
  = stylesheet_link_tag    "application", :media => "all"
  = javascript_include_tag "http://js.pusher.com/1.12/pusher.min.js"
  = javascript_include_tag "application"
  = csrf_meta_tags
body
  .container
    .row
      .span12
        - if content_for? :header
          .page-header
            h1= content_for :header
        - if notice
          .alert.alert-success= notice
        - if alert
          .alert.alert-error= alert            
        = yield
  .footer
    .container
      =' link_to "Plus", "http://thenounproject.com/noun/plus/#icon-No2876", target: "_blank"
      ' designed by
      =' link_to  "P.J. Onori", "http://thenounproject.com/somerandomdude", target: "_blank"
      | from The Noun Project
      br
      =' link_to "Pencil", "http://thenounproject.com/noun/pencil/#icon-No347", target: "_blank"
      | from The Noun Project
      br
      =' link_to "Trash Can", "http://thenounproject.com/noun/trash-can/#icon-No5700", target: "_blank"
      ' designed by
      =' link_to "Maximilian Becker", "http://thenounproject.com/AchtSieben", target: "_blank"
      | from The Noun Project
.navbar.navbar-fixed-top
  .navbar-inner
    .container
        ul.nav
          li= link_to "Posts", root_path
          li= link_to "News feed", feed_path          
          li= link_to "Your actions", your_actions_path
        ul.nav.pull-right
          - if user_signed_in?
            li= link_to current_user.nickname, user_path(current_user)
            li= link_to "Sign out", destroy_user_session_path, method: :delete
          - else
            li= link_to "Sign in with Github", omniauth_authorize_path(:user, :github)

app/views/posts/_form.slim
= simple_form_for(@post, html: {class: 'form-horizontal' }) do |f|
  = f.input :title
  = f.input :body
  .form-actions
    = f.button :submit

app/views/posts/_post.slim
.row
  .activity.post
    .body
      h2
        =' link_to post.title, post
        small.pull-right= timeago post.created_at
      .details
        .avatar
          = image_tag post.author.avatar_url, width: "30", height: "30", title: post.author.nickname
        div= post.body
        div.pull-right
          = link_to "Comments (#{post.comments.count})", post

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.slim
div.clearfix
  = link_to "+ New post", new_post_path, class: "btn btn-large btn-success pull-right"


= render @posts

app/views/posts/new.slim
- content_for :header, "Create new post"

= render 'form'

= link_to 'Back', posts_path

app/views/posts/show.slim
.row
  .span9
    .page-header
      h1
        = @post.title
        small.pull-right= timeago @post.created_at
    = @post.body

    hr
    - if @post.author == current_user
      = link_to "Remove this post", @post, method: :delete
    br
    br
    br
    br

    h2 
      ' Comments
      small= "(#{@post.comments.count})"
    = render @comments
    
    - if user_signed_in?
      = render :partial => "comments/form"


  .span3.activities-sidebar
    h3 Post's activity

    - for activity in @activities
      = render_activity(activity, :layout => "layouts/activity_wrapper")

app/views/public_activity/post/_commented.slim
- single_content_for :action do
  ' commented on
  =' whose?(a.owner, a.trackable)
  = link_to_trackable a.trackable, a.trackable_type

= p[:comment]

app/views/public_activity/post/_create.slim
- single_content_for :action do
  ' created a new 
  = link_to_trackable a.trackable, a.trackable_type

= p[:summary]

app/views/public_activity/post/_destroy.slim
- single_content_for :action do
  ' removed a
  = a.trackable_type.downcase

= p[:summary]

app/views/public_activity/post/_update.slim
- single_content_for :action do
  ' edited
  =' whose?(a.owner, a.trackable)
  = link_to_trackable a.trackable, a.trackable_type

= p[:summary]

app/views/users/show.slim
= @user